In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
results_pension = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MDS - Grupo 7/Capstone/Propensión/results_pension_plan.csv')
results_debit = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MDS - Grupo 7/Capstone/Propensión/results_debit.csv')
results_ema = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MDS - Grupo 7/Capstone/Propensión/results_ema.csv')
results_payroll = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MDS - Grupo 7/Capstone/Propensión/results_payroll.csv')
results_emc = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MDS - Grupo 7/Capstone/Propensión/results_emc.csv')

In [ ]:
results_ema.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4190 entries, 0 to 4189
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   pk_cid                  4190 non-null   int64
 1   Probability_ema_acount  4190 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 65.6 KB

In [ ]:
results_pension.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 389939 entries, 0 to 389938
Data columns (total 2 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   pk_cid                    389939 non-null  int64
 1   Probability_pension_plan  389939 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 6.0 MB

In [ ]:
results_debit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326933 entries, 0 to 326932
Data columns (total 2 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   pk_cid             326933 non-null  int64
 1   Probability_debit  326933 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 5.0 MB

In [ ]:
results_payroll.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392370 entries, 0 to 392369
Data columns (total 2 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   pk_cid               392370 non-null  int64
 1   Probability_payroll  392370 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 6.0 MB

In [ ]:
results_emc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391005 entries, 0 to 391004
Data columns (total 2 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   pk_cid                   391005 non-null  int64
 1   Probability_emc_account  391005 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 6.0 MB

In [ ]:
# Primero, unimos los dos primeros dataframes
df_merged = pd.merge(results_pension, results_debit, on='pk_cid', how='outer')

# Luego unimos los siguientes dataframes, uno por uno
df_merged = pd.merge(df_merged, results_payroll, on='pk_cid', how='outer')
df_merged = pd.merge(df_merged, results_ema, on='pk_cid', how='outer')
df_merged = pd.merge(df_merged, results_emc, on='pk_cid', how='outer')

In [ ]:
df_merged.head()

,pk_cid,Probability_pension_plan,Probability_debit,Probability_payroll,Probability_ema_acount,Probability_emc_account
0,1519449,0.997460,NaN,0.923888,NaN,NaN
1,1514174,0.997218,NaN,0.946946,NaN,0.826089
2,1382623,0.995947,NaN,0.787060,NaN,0.724986
3,901017,0.995877,NaN,0.802506,NaN,NaN
4,1413895,0.995702,NaN,0.826743,NaN,0.260449

In [ ]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 437056 entries, 0 to 437055
Data columns (total 6 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   pk_cid                    437056 non-null  int64
 1   Probability_pension_plan  389939 non-null  float64
 2   Probability_debit         326933 non-null  float64
 3   Probability_payroll       392370 non-null  float64
 4   Probability_ema_acount    4190 non-null    float64
 5   Probability_emc_account   391005 non-null  float64
dtypes: float64(5), int64(1)
memory usage: 23.3 MB

In [ ]:
# Verifica si hay duplicados basado en la columna 'pk_cid'
duplicates = df_merged.duplicated(subset='pk_cid')

# Imprime el número de duplicados
print(f"Number of duplicate rows based on 'pk_cid': {duplicates.sum()}")

# Si quieres ver los duplicados, puedes hacerlo así:
print(df_merged[df_merged.duplicated(subset='pk_cid', keep=False)].sort_values(by='pk_cid'))

Number of duplicate rows based on 'pk_cid': 0
Empty DataFrame
Columns: [pk_cid, Probability_pension_plan, Probability_debit, Probability_payroll, Probability_ema_acount, Probability_emc_account]
Index: []

In [ ]:
from google.colab import files

# Guardar el dataframe en un archivo CSV
df_merged.to_csv('df_merged.csv', index=False)

# Descargar el archivo CSV
files.download('df_merged.csv')